version: "3.7"

services:

  openproject:
    container_name: openproject
    build:
      context: openproject
    ports:
      - 5432:5432
      - 8090:80

  gitbucket:
    container_name: gitbucket
    build: 
      context: gitbucket
    ports:
      - "8080:8080"
      - "29418:29418"

  drone-server:
    container_name: drone-server
    image: drone/drone:latest
    ports:
      - 80:8000
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost:8000
      - DRONE_GITBUCKET_URL=http://localhost:8080
      - DRONE_GITBUCKET=true

  drone-agent:
    container_name: drone-agent
    image: drone/agent:latest
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=localhost:9000
